---
title: "03-references"
author: "Chloe"
date: "5/14/2020"
output: html_document
---
# References 

Au, J. (2011). A Longitudinal Study Examining the Role of Social Connectedness in the Course
of Depressive Symptoms: An Evaluation of Transfer and Freshman
Students(Unpublished doctoral dissertation ). University of Michigan.

Beck, A. T., & Steer, R. A. (1993). Beck Anxiety Inventory Manual . San Antonio, TX: The
Psychological Corporation Harcourt Brace & Company.

Buysse, D. J., Reynolds, C. F., Monk, T. H., Berman, S. R., & Kupfer, D. J. (1989). The
Pittsburgh Sleep Quality Index: A new instrument for psychiatric practice and research.
Psychiatry Research, 28 (2), 193–213. https://doi.org/10.1016/0165-1781(89)90047-4

Clance, P. R. (1986). The impostor phenomenon: when success makes you feel like a fake . New
York: Bantam Books.

Cohen, S., Kamarck, T., and Mermelstein, R. (1983). A global measure of perceived stress.
Journal of Health and Social Behavior , 24, 386-396.
College Transfer Pathway. Journal of Women and Minorities in Science and Engineering, 17 (2),129-147. doi:10.1615/jwomenminorscieneng.2011002470

Duckworth, A. L., Peterson, C., Matthews, M. D., & Kelly, D. R. (2007). Grit: Perseverance and passion for long-term goals. Journal of Personality and Social Psychology , 92 (6),
1087–1101. doi:10.1037/0022-3514.92.6.1087

Dweck, C. S. (2006). Mindset: The new psychology of success. New York: Random House.
Find out your financial well-being. (n.d.). Retrieved December 10, 2019, from
https://www.consumerfinance.gov/consumer-tools/financial-well-being/.

Gallagher, R. P. (2008). National Survey of Counseling Directors. The American College
Counseling Association.

Lovibond, S. H., & Lovibond, P. F. (1995). Manual for the Depression Anxiety Stress Scales
(2nd ed.). Sydney: Psychology Foundation of Australia.

Mackenzie, S., Wiegel, J. R., Mundt, M., Brown, D., Saewyc, E., Heiligenstein, E., … Fleming,M. (2011). Depression and suicide ideation among students accessing campus health
care. American Journal of Orthopsychiatry , 81 (1), 101–107. doi:10.1111/j.1939-0025.2010.01077.

Mehr, K. E., & Daltry, R. (2016). Examining Mental Health Differences between Transfer and
Nontransfer University Students Seeking Counseling Services. Journal of College
Student Psychotherapy, 30 (2), 146-155. doi:10.1080/87568225.2016.1140996

Packard, B. W., Gagnon, J. L., Labelle, O., Jeffers, K., & Lynn, E. (2011). Womens Experiences In The Stem Community Rhine, T. J., Milligan, D. M., Nelson, L. R. (2000). Alleviating Transfer Shock: Creating An Environment For More Successful Transfer Students. Community College Journal of Research and Practice, 24 (6), 443-453. doi:10.1080/10668920050137228

Tennant, R., Hiller, L., Fishwick, R., Platt, S., Joseph, S., Weich, S., Parkinson, J., Secker, J., & Stewart-Brown, S. (2007). The Warwick-Edinburgh Mental Well-being Scale
(WEMWBS): Development and UK validation. Health and Quality of Life Outcomes, 5,
Article 63. https://doi.org/10.1186/1477-7525-5-63

Townsend, B. K., & Wilson, K. B. (2009). The Academic and Social Integration of Persisting
Community College Transfer Students. doi:10.2190/CS.10.4.a

Vazquez , R. (2018, July 11). UCLA offers freshman admission to 16,000, increases offers to
transfer students. Retrieved from
http://newsroom.ucla.edu/releases/ucla-offers-freshman-admission-to-16-000-increases-offers-to-transfer-students

Zimet, G.D., Dahlem, N.W., Zimet, S.G. & Farley, G.K. (1988). The Multidimensional Scale of
Perceived Social Support. Journal of Personality Assessment , 52, 30-41.